// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp7WGq1zk1NtEEIk8BBInsbTY48LIU1RM',
    appId: '1:387582206707:web:f260cc072de88459288d86',
    messagingSenderId: '387582206707',
    projectId: 'laundrygogo-sp1729',
    authDomain: 'laundrygogo-sp1729.firebaseapp.com',
    storageBucket: 'laundrygogo-sp1729.firebasestorage.app',
    measurementId: 'G-H21WYZC084',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgtdQxJdkUVc12pE64bIPmWGw_y3PtUhY',
    appId: '1:387582206707:android:8d4669a08358a0c0288d86',
    messagingSenderId: '387582206707',
    projectId: 'laundrygogo-sp1729',
    storageBucket: 'laundrygogo-sp1729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWcNhg5b5MydJWNgVaEgkSkbbs-gwu8zY',
    appId: '1:387582206707:ios:efabc126c1bed725288d86',
    messagingSenderId: '387582206707',
    projectId: 'laundrygogo-sp1729',
    storageBucket: 'laundrygogo-sp1729.firebasestorage.app',
    androidClientId: '387582206707-5oc3r7cm5g18ro47vnlo32n5d3mj0g8l.apps.googleusercontent.com',
    iosClientId: '387582206707-h0fck1kbd4km1o6amsvs5f36a90iale6.apps.googleusercontent.com',
    iosBundleId: 'com.chauhaddi.korba.korba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWcNhg5b5MydJWNgVaEgkSkbbs-gwu8zY',
    appId: '1:387582206707:ios:efabc126c1bed725288d86',
    messagingSenderId: '387582206707',
    projectId: 'laundrygogo-sp1729',
    storageBucket: 'laundrygogo-sp1729.firebasestorage.app',
    androidClientId: '387582206707-5oc3r7cm5g18ro47vnlo32n5d3mj0g8l.apps.googleusercontent.com',
    iosClientId: '387582206707-h0fck1kbd4km1o6amsvs5f36a90iale6.apps.googleusercontent.com',
    iosBundleId: 'com.chauhaddi.korba.korba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp7WGq1zk1NtEEIk8BBInsbTY48LIU1RM',
    appId: '1:387582206707:web:4a0a5aa8ccb95464288d86',
    messagingSenderId: '387582206707',
    projectId: 'laundrygogo-sp1729',
    authDomain: 'laundrygogo-sp1729.firebaseapp.com',
    storageBucket: 'laundrygogo-sp1729.firebasestorage.app',
    measurementId: 'G-RTRVD43FBM',
  );
}
